ip: 192.168.94.174
password: raqFUHQ2
calibration:
  angle:
    # max = turn left, min = turn right
    max: 25
    mid: 10
    min: -20
    polarity: 1

  throttle:
    # max = reverse max speed, mid = zero speed, min = forward max speed
    max: 40
    mid: -12
    min: -40
    polarity: -1
    
